name: GitHub Action
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolache
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pylint
      - name: Lint with flake8
        run: |
          flake8 python_fu_cartoonify.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 python_fu_cartoonify.py --count --max-complexity=10 --max-line-length=79 --statistics
      - name: Lint with Pylint
        run: |
          pylint python_fu_cartoonify.py